#!/usr/bin/env bash
# Transfer a file to a server

if [ "$4" ] ; then
  PATH_TO_FILE="$1"
  IP="$2"
  USERNAME="$3"
  SSH_KEY="$4"
  scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
else
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
