#!/usr/bin/env bash
# update
# Install nginx
# listen to port 80
# allow nginx on firewall
# update nginx index page
# restart nginx

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
