#!/usr/bin/env bash
# 404 page
# Redirecting traffic using nginx
# update
# Install nginx
# listen to port 80
# allow nginx on firewall
# update nginx index page
# restart Nginx

DESTINATION_URL="https://github.com/devbojack"
ERROR_STRING="Ceci n'est pas une page"
ERROR_LOCATION="location = /404.html {\n\t\troot /var/www/html/;\n\t\tinternal;\n"
ERROR_D="error_page 404 /404.html;\n\t$ERROR_LOCATION"
ERROR_404="}\n\n\t$ERROR_D\t}"
CONFIG_SHC="server_name _;\n\trewrite ^/redirect_me/$ $DESTINATION_URL permanent;"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo ERROR_STRING > /var/www/html/404.html
sed -i "s|server_name\ _;|$CONFIG_SHC|" /etc/nginx/sites-available/default
sed -i "0,/}/ s|}|$ERROR_404|" /etc/nginx/sites-available/default
sudo service nginx restart
