#!/usr/bin/env bash
# 404 page
# Redirecting traffic using nginx
# update
# Install nginx
# listen to port 80
# allow nginx on firewall
# update nginx index page
# restart Nginx

DESTINATION_URL="https://github.com/devbojack"

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me $DESTINATION_URL permanent;" /etc/nginx/sites-available/default
sudo sed -i 's@error_page 404 /usr/share/nginx/html/;@error_page 404 /var/www/html/404.html;@' /etc/nginx/sites-available/default
sudo service nginx restart
